### ISSUE TITLE
I can easily open BPMN files from the local file system

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-io-chrome#6]
Users should be able to open BPMN files via the local file system / finder / explorer application

### Tasks

* [ ] double click on `*.bpmn` files leads to opening in chrome app

### Notes

* [ ] this is also possible from an IDE (like eclipse)

**Comment by ricardomatias** [comment]
At the moment it isn't possible to do this and there's no ETA.

**Comment by nikku** [comment]
@ricardomatias Where did you find this information?

**Comment by ricardomatias** [comment]
Changes are in this [commit](https://github.com/bpmn-io/bpmn-io-chrome/commit/2ec06cfc48512c3a77bcda0a5be1df72cce7143d).

**Comment by ricardomatias** [comment]
This works only for mac. Windows and Linux users have to wait for certain changes. 
[StackOverflow Discussion](http://stackoverflow.com/questions/22632876/associate-file-type-with-chrome-packaged-app)

**Comment by menski** [comment]
For the Linux folks you could provide a desktop, mimetype file and a guide how to register them locally. This would allow them to also open BPMN files by double click. If this would be a solution I could help with that.

**Comment by ricardomatias** [comment]
[Node-webkit](https://github.com/nwjs/nw.js)
[nw - github File extension issue](https://github.com/nwjs/nw.js/issues/255)
