### ISSUE TITLE
I can read about a bpmn.io offline modeling solution (on bpmn.io)

### ISSUE THREAD

**Issue by gimbel** [bpmn-io/bpmn-io-chrome#9]
Add a landing page for the chrome app at [bpmn.io/offline](http://bpmn.io/offline).

* [x] hint on where the app can be downloaded
* [x] add documentation on how to open `.bpmn` files locally using the app

**Comment by ricardomatias** [comment]
Naming suggestions:
- Desktop Application
- Standalone Application
